### ISSUE TITLE
No ethernet and USB

### ISSUE THREAD

**Issue by tiagopvb** [diegoherranz/RPiCM-LAN-DT#1]
Hi Diego,

I just developed a board using the CM and the smsc9514. I use my own oscillator instead of GPIO44. I use the pin GPIO31 for the reset. 

I changed the dtbs as per your instructions but I can't get the chip to work. I see the driver for the smsc95xx being loaded by the kernel and I even get two USB hubs when doing lsusb. 

My firmware is from Feb 2015. 

Do you know what the issue could be?

Thank you.

Regards.

**Comment by tiagopvb** [comment]
Hi, issue solved. It seems it was a defect in the PCB. Changed it to a new one and it works perfectly now.

**Comment by diegoherranz** [comment]
I'm glad it worked for you.

Diego
